### PR TITLE
Add color theme selection box

### PR DESCRIPTION
**Pull request by tostercx**
...and install instructions. It finds the first .clr file in the skin's folder and shows it's path for easier installation.

also included .clr files for current skins. Sources:

https://raw.githubusercontent.com/eugeii/ida-consonance/master/ida-consonance.clr
https://raw.githubusercontent.com/williballenthin/idawilli/master/themes/colors/adwaita-dark/adwaita-dark.clr

### CODE REVIEW

**Comment by tostercx** [comment]
Hmm... noticed a weird bug. On windows if I open a project by drag-dropping and then go to skin selection, click on the .clr path in the edit box - the path gets deselected making it hard to copy.

I had set up a `selectionChanged` trigger for that but it doesn't seem to be firing after a drag-drop. Wonder if it's a bug in Qt itself or something. Opening a project from the menu doesn't trigger it.

**Comment by athre0z** [comment]
Thanks! I merged this into the [`develop`](https://github.com/zyantific/IDASkins/tree/develop) branch and GitHub doesn't seem to detect it as merge, so I'll just close this, but the changes are still merged.

**Comment by athre0z** [comment]
The auto-select was pretty bugged, probably due to some Qt stuff. I removed it and added a "Copy" button instead. Also, I rewrote the whole plugin in Python.

**Comment by tostercx** [comment]
Oh yeah, that solves it! Also clicking a button is more obvious than focusing the box and hitting ctrl+c. Nice work! :)

What made you rewrite it to python tho? Not that I mind it. Compiling on windows was a PITA.

**Comment by athre0z** [comment]
Exactly that. Compiling on macOS and Linux is even worse since it requires licenses for all the platforms (you link directly against IDA on these platforms, not the SDK, so you need to have the binaries) and since I certainly won't buy additional platforms just to support a free plugin, shipping it in Python seemed to be the only sane choice.

**Comment by tostercx** [comment]
Nice! It's already working. Did you do all of that in a single day? O_O
Btw I'm not sure why, it's not picking up the clr file for the default skin for me. Hmm.

**Comment by athre0z** [comment]
Haha, yeah, I did. It took about 3-4 hours "yesterday" (aka: before sleeping) for the port and another 30 minutes today for a bit of clean-up and the "Copy" button. I write a lot of Python and the PyQt maps pretty much 1:1, so it was pretty straightforward. Also, I switched the manifests to JSON which is a lot easier to parse in Py. I think the whole plugin is like 1/3 the amount of code of the C++ version.

Yep, I switched that to be consistent with the preview image. I'll also change `stylesheet.qss` to be configurable again soon. Seems like I forgot to add the CLR file for the default skin, thanks for pointing that out! Just pushed a commit that fixes it.

**Comment by athre0z** [comment]
Did you happen to test with 7.0? I only have 7.1 installed and it'd be neat to know if it works with 7.0 as well.

**Comment by tostercx** [comment]
Yepp `Version 7.0.170914 Windows x64`
Seems to work fine!

**Comment by athre0z** [comment]
Excellent, thanks!

**Pull request closed without merging**
