### PR TITLE
VSCode dark theme

### PR DESCRIPTION
**Pull request by Jinmo**
Adjusted for windows font sizes.

### CODE REVIEW

**Comment by athre0z** [comment]
Looks absolutely glorious, thanks! 

What IDA version are you developing this with? 7.0? The theme is having some of the same issues my themes had before I updated them for 7.2, e.g. misaligned close buttons and gigantic arrows in the nav bar. I assume this isn't intended?

Screen Shot 2019-05-21 at 07 28 31

**Comment by athre0z** [comment]
If you don't have a copy of 7.2 at hand, I can take a look at it myself, should be no big deal.

For reference, these were my 7.2 fixes for `idaskins-dark`:
https://github.com/zyantific/IDASkins/commit/3d707c6aae5a614e24ac089947dea3ba9ed41f8a
https://github.com/zyantific/IDASkins/commit/69d4f9704da09794b85fbb9095cc161336682963

**Comment by Jinmo** [comment]
Thanks for the feedback! I've added these lines but cannot test on 7.2... Also added .less file for ease of editing.

**Comment by athre0z** [comment]
Thank you! That's pretty cool, I didn't know it was possible to use LESS for QSS!

The 7.2 fixes work! This is how it looks now:
KFEQ6EkkysdztnNU
Please take a final look and let me know if everything is looking as intended in 7.2 (as far as you can see on the screenshot) before I merge this.

**Comment by Jinmo** [comment]
Yeah, seems like it's working fine. :+1:

**Comment by athre0z** [comment]
Excellent. Thank you very much for this! I think this is legitimately the best theme we have now, I'll probably replace the screenshot in the repo or at least add one of this theme.

**Comment by athre0z** [comment]
Do you plan on dropping any more PRs in the next few days? If you're done for now, I'd like to wrap these changes into a new release.

**Comment by Jinmo** [comment]
Currently I don't. It sounds cool!

**Comment by athre0z** [comment]
One last thing I didn't see before: in graph view, the background is still very bright. I'd like to make that a little darker (the color of the menu/tool-bar). Would that be fine with you?

Before:
hKIKC8tiVxqGnlFk

After:
IGxxK6NKjqvTEePZ

**Comment by Jinmo** [comment]
Yep, great!

**Comment by athre0z** [comment]
https://github.com/zyantific/IDASkins/releases/tag/v2.1.0

There we go!

**Pull request merged**
